baseURL = "https://abhishekbagalkot.com/"
languageCode = "en-us"
title = "Abhishek Bagalkot"
enableRobotsTXT = true

[taxonomies]
  category = "categories"

[params]
  cloudflareAnalytics = "9ab84ba8c01446cdb621932f259f28ae"   # delete this line to remove analytics
  x = "https://x.com/abhibagalkot"
  linkedin = "https://www.linkedin.com/in/abhishekbagalkot/"
  categoryNav = ["Business", "Technology", "Essays", "Stories"]
  ogImage = "img/og-card.png"
  description = "Writings on Business, Technology & Society"

[markup.goldmark.renderer]
  unsafe = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Writings"
  url = "/posts/"
  weight = 2
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
